---
abstract: 'Perl module to use HTML-like templating language'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Template
requires:
  Carp: 0
  Digest::MD5: 0
  File::Spec: 0.82
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0
version: 2.10_1
